spring:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: false

  flyway:
    enabled: true
    schemas: sc_cabko
    defaultSchema: sc_cabko
    locations: classpath:db/migration
    cleanDisabled: false # ENABLED FOR DEV, do NOT use in production
    clean-on-migration-validation-error: true

  docker:
    compose:
      enabled: true
      file:
        - ../docker-compose-postgreSQL.yml

# 256 bit or more
jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
        boot:
          autoconfigure: INFO

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true